[2025-02-18T04:31:06.117+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-18T04:31:06.142+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_first_dag.hello_task scheduled__2024-03-28T00:00:00+00:00 [queued]>
[2025-02-18T04:31:06.150+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_first_dag.hello_task scheduled__2024-03-28T00:00:00+00:00 [queued]>
[2025-02-18T04:31:06.151+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-02-18T04:31:06.165+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): hello_task> on 2024-03-28 00:00:00+00:00
[2025-02-18T04:31:06.171+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=359) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-18T04:31:06.171+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'my_first_dag', 'hello_task', 'scheduled__2024-03-28T00:00:00+00:00', '--job-id', '42', '--raw', '--subdir', 'DAGS_FOLDER/my-first-dag.py', '--cfg-path', '/tmp/tmpq6bd8hrh']
[2025-02-18T04:31:06.174+0000] {standard_task_runner.py:72} INFO - Started process 367 to run task
[2025-02-18T04:31:06.176+0000] {standard_task_runner.py:105} INFO - Job 42: Subtask hello_task
[2025-02-18T04:31:06.199+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-02-18T04:31:06.266+0000] {task_command.py:467} INFO - Running <TaskInstance: my_first_dag.hello_task scheduled__2024-03-28T00:00:00+00:00 [running]> on host 3420485c558b
[2025-02-18T04:31:06.270+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-02-18T04:31:06.384+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='my_first_dag' AIRFLOW_CTX_TASK_ID='hello_task' AIRFLOW_CTX_EXECUTION_DATE='2024-03-28T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-28T00:00:00+00:00'
[2025-02-18T04:31:06.396+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-18T04:31:06.428+0000] {logging_mixin.py:190} INFO - Hello, Airflow!
[2025-02-18T04:31:06.436+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-18T04:31:06.453+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-18T04:31:06.456+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=my_first_dag, task_id=hello_task, run_id=scheduled__2024-03-28T00:00:00+00:00, execution_date=20240328T000000, start_date=20250218T043106, end_date=20250218T043106
[2025-02-18T04:31:06.577+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-18T04:31:06.597+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-02-18T16:34:09.138+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-18T16:34:09.175+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_first_dag.hello_task scheduled__2024-03-28T00:00:00+00:00 [queued]>
[2025-02-18T16:34:09.199+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_first_dag.hello_task scheduled__2024-03-28T00:00:00+00:00 [queued]>
[2025-02-18T16:34:09.206+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-02-18T16:34:09.231+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): hello_task> on 2024-03-28 00:00:00+00:00
[2025-02-18T16:34:09.248+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=1641) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-18T16:34:09.258+0000] {standard_task_runner.py:72} INFO - Started process 1654 to run task
[2025-02-18T16:34:09.258+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'my_first_dag', 'hello_task', 'scheduled__2024-03-28T00:00:00+00:00', '--job-id', '410', '--raw', '--subdir', 'DAGS_FOLDER/my-first-dag.py', '--cfg-path', '/tmp/tmpi5mp6xx_']
[2025-02-18T16:34:09.263+0000] {standard_task_runner.py:105} INFO - Job 410: Subtask hello_task
[2025-02-18T16:34:09.303+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-02-18T16:34:09.487+0000] {task_command.py:467} INFO - Running <TaskInstance: my_first_dag.hello_task scheduled__2024-03-28T00:00:00+00:00 [running]> on host 8720d9c228eb
[2025-02-18T16:34:09.490+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-02-18T16:34:09.754+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='my_first_dag' AIRFLOW_CTX_TASK_ID='hello_task' AIRFLOW_CTX_EXECUTION_DATE='2024-03-28T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-28T00:00:00+00:00'
[2025-02-18T16:34:09.763+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-18T16:34:09.796+0000] {logging_mixin.py:190} INFO - Hello, Airflow!
[2025-02-18T16:34:09.804+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-18T16:34:09.844+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-18T16:34:09.850+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=my_first_dag, task_id=hello_task, run_id=scheduled__2024-03-28T00:00:00+00:00, execution_date=20240328T000000, start_date=20250218T163409, end_date=20250218T163409
[2025-02-18T16:34:09.948+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-18T16:34:09.995+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-18T16:34:10.004+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
